import os
from dotenv import load_dotenv

from openai import OpenAI
from langchain_community.document_loaders import CSVLoader
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

load_dotenv()

# 1) Try environment variable (for local use)
# 2) Fall back to Streamlit secrets (for Streamlit Cloud)
api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    try:
        import streamlit as st
        api_key = st.secrets.get("OPENAI_API_KEY")
    except Exception:
        pass

if not api_key:
    raise RuntimeError(
        "OPENAI_API_KEY is not set. "
        "Set it in a .env file (local) or in Streamlit Secrets (cloud)."
    )

client = OpenAI(api_key=api_key)

# Where the FAISS index will be stored
VECTOR_DB_FILE_PATH = "faiss_index"

# Embedding model (small + fast)
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

# Ontario Tech FAQ CSV (generated by your scraper)
FAQ_CSV_FILE = "ontario_tech_faqs.csv"

# Fixed response for anything NOT in the FAQ (no OpenAI tokens used)
FALLBACK_RESPONSE = (
    "Your question falls outside the scope of what I can assist with. "
    "I'm here to help with Ontario Tech University inquiries such as "
    "admissions, fees, registration, and financial aid."
)

# Similarity threshold: if best match is weaker than this, skip the LLM.
# For FAISS distance scores: LOWER = more similar, HIGHER = less similar.
RELEVANCE_SCORE_THRESHOLD = 1.0


def _get_embeddings():
    """Create the embedding model (same config for save/load)."""
    return HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL_NAME)


def create_vector_db():
    """Create FAISS index from the Ontario Tech FAQ CSV and save it locally."""
    if not os.path.exists(FAQ_CSV_FILE):
        raise FileNotFoundError(
            f"Could not find '{FAQ_CSV_FILE}'. "
            "Make sure ontario_tech_faqs.csv is in the same folder as this app."
        )

    loader = CSVLoader(
        file_path=FAQ_CSV_FILE,
        encoding="utf-8",
        source_column="Question",
        metadata_columns=["Section"],
    )
    docs = loader.load()

    embeddings = _get_embeddings()
    vectordb = FAISS.from_documents(documents=docs, embedding=embeddings)
    vectordb.save_local(VECTOR_DB_FILE_PATH)

    return vectordb


def ensure_vector_db():
    """
    Load existing FAISS index if present; otherwise build a new one.
    Streamlit will call this once and reuse the result.
    """
    embeddings = _get_embeddings()

    if os.path.isdir(VECTOR_DB_FILE_PATH):
        return FAISS.load_local(
            VECTOR_DB_FILE_PATH,
            embeddings,
            allow_dangerous_deserialization=True,
        )
    else:
        return create_vector_db()


def answer_question(question: str, vectordb) -> str:
    """
    Retrieve relevant docs and ask OpenAI for an answer.
    If the question is NOT relevant to the Ontario Tech FAQ CSV (weak similarity),
    return a fixed fallback response WITHOUT calling OpenAI (0 tokens).
    """
    question = (question or "").strip()
    if not question:
        return FALLBACK_RESPONSE

    # Use scores so we can decide whether to call the LLM
    results = vectordb.similarity_search_with_score(question, k=4)

    if not results:
        return FALLBACK_RESPONSE

    best_score = results[0][1]

    # If not relevant enough -> skip the model (no tokens used)
    if best_score > RELEVANCE_SCORE_THRESHOLD:
        return FALLBACK_RESPONSE

    docs = [doc for doc, _score in results]
    context = "\n\n".join(d.page_content for d in docs)

    prompt = f"""
    You are an assistant answering questions about Ontario Tech University Admissions.

    Use the context below when it is relevant. If the context does not give an exact answer,
    reply with a short, generic but helpful answer based on typical university admissions practices.
    Do NOT say "I don't know" and do NOT invent specific names, numbers, or policies.

    Context:
    {context}

    User question: {question}

    Answer clearly in 2–4 sentences:
    """.strip()

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=120,
    )

    return response.choices[0].message.content.strip()
